class Countrys {
  String CountrysName;
  String CountrysCode;

  Countrys({
    required this.CountrysName,
    required this.CountrysCode,
  });
}

List<Countrys> CountrysList = [
  Countrys(CountrysName: 'Afghanistan', CountrysCode: 'AF'),
  Countrys(CountrysName: 'Åland Islands', CountrysCode: 'AX'),
  Countrys(CountrysName: 'Albania', CountrysCode: 'AL'),
  Countrys(CountrysName: 'Algeria', CountrysCode: 'DZ'),
  Countrys(CountrysName: 'American Samoa', CountrysCode: 'AS'),
  Countrys(CountrysName: 'AndorrA', CountrysCode: 'AD'),
  Countrys(CountrysName: 'Angola', CountrysCode: 'AO'),
  Countrys(CountrysName: 'Anguilla', CountrysCode: 'AI'),
  Countrys(CountrysName: 'Antarctica', CountrysCode: 'AQ'),
  Countrys(CountrysName: 'Antigua and Barbuda', CountrysCode: 'AG'),
  Countrys(CountrysName: 'Argentina', CountrysCode: 'AR'),
  Countrys(CountrysName: 'Armenia', CountrysCode: 'AM'),
  Countrys(CountrysName: 'Aruba', CountrysCode: 'AW'),
  Countrys(CountrysName: 'Australia', CountrysCode: 'AU'),
  Countrys(CountrysName: 'Austria', CountrysCode: 'AT'),
  Countrys(CountrysName: 'Azerbaijan', CountrysCode: 'AZ'),
  Countrys(CountrysName: 'Bahamas', CountrysCode: 'BS'),
  Countrys(CountrysName: 'Bahrain', CountrysCode: 'BH'),
  Countrys(CountrysName: 'Bangladesh', CountrysCode: 'BD'),
  Countrys(CountrysName: 'Barbados', CountrysCode: 'BB'),
  Countrys(CountrysName: 'Belarus', CountrysCode: 'BY'),
  Countrys(CountrysName: 'Belgium', CountrysCode: 'BE'),
  Countrys(CountrysName: 'Belize', CountrysCode: 'BZ'),
  Countrys(CountrysName: 'Benin', CountrysCode: 'BJ'),
  Countrys(CountrysName: 'Bermuda', CountrysCode: 'BM'),
  Countrys(CountrysName: 'Bhutan', CountrysCode: 'BT'),
  Countrys(CountrysName: 'Bolivia', CountrysCode: 'BO'),
  Countrys(CountrysName: 'Bosnia and Herzegovina', CountrysCode: 'BA'),
  Countrys(CountrysName: 'Botswana', CountrysCode: 'BW'),
  Countrys(CountrysName: 'Bouvet Island', CountrysCode: 'BV'),
  Countrys(CountrysName: 'Brazil', CountrysCode: 'BR'),
  Countrys(CountrysName: 'British Indian Ocean Territory', CountrysCode: 'IO'),
  Countrys(CountrysName: 'Brunei Darussalam', CountrysCode: 'BN'),
  Countrys(CountrysName: 'Bulgaria', CountrysCode: 'BG'),
  Countrys(CountrysName: 'Burkina Faso', CountrysCode: 'BF'),
  Countrys(CountrysName: 'Burundi', CountrysCode: 'BI'),
  Countrys(CountrysName: 'Cambodia', CountrysCode: 'KH'),
  Countrys(CountrysName: 'Cameroon', CountrysCode: 'CM'),
  Countrys(CountrysName: 'Canada', CountrysCode: 'CA'),
  Countrys(CountrysName: 'Cape Verde', CountrysCode: 'CV'),
  Countrys(CountrysName: 'Cayman Islands', CountrysCode: 'KY'),
  Countrys(CountrysName: 'Central African Republic', CountrysCode: 'CF'),
  Countrys(CountrysName: 'Chad', CountrysCode: 'TD'),
  Countrys(CountrysName: 'Chile', CountrysCode: 'CL'),
  Countrys(CountrysName: 'China', CountrysCode: 'CN'),
  Countrys(CountrysName: 'Christmas Island', CountrysCode: 'CX'),
  Countrys(CountrysName: 'Cocos (Keeling) Islands', CountrysCode: 'CC'),
  Countrys(CountrysName: 'Colombia', CountrysCode: 'CO'),
  Countrys(CountrysName: 'Comoros', CountrysCode: 'KM'),
  Countrys(CountrysName: 'Congo', CountrysCode: 'CG'),
  Countrys(
      CountrysName: 'Congo, The Democratic Republic of the',
      CountrysCode: 'CD'),
  Countrys(CountrysName: 'Cook Islands', CountrysCode: 'CK'),
  Countrys(CountrysName: 'Costa Rica', CountrysCode: 'CR'),
  Countrys(CountrysName: 'Cote D\'Ivoire', CountrysCode: 'CI'),
  Countrys(CountrysName: 'Croatia', CountrysCode: 'HR'),
  Countrys(CountrysName: 'Cuba', CountrysCode: 'CU'),
  Countrys(CountrysName: 'Cyprus', CountrysCode: 'CY'),
  Countrys(CountrysName: 'Czech Republic', CountrysCode: 'CZ'),
  Countrys(CountrysName: 'Denmark', CountrysCode: 'DK'),
  Countrys(CountrysName: 'Djibouti', CountrysCode: 'DJ'),
  Countrys(CountrysName: 'Dominica', CountrysCode: 'DM'),
  Countrys(CountrysName: 'Dominican Republic', CountrysCode: 'DO'),
  Countrys(CountrysName: 'Ecuador', CountrysCode: 'EC'),
  Countrys(CountrysName: 'Egypt', CountrysCode: 'EG'),
  Countrys(CountrysName: 'El Salvador', CountrysCode: 'SV'),
  Countrys(CountrysName: 'Equatorial Guinea', CountrysCode: 'GQ'),
  Countrys(CountrysName: 'Eritrea', CountrysCode: 'ER'),
  Countrys(CountrysName: 'Estonia', CountrysCode: 'EE'),
  Countrys(CountrysName: 'Ethiopia', CountrysCode: 'ET'),
  Countrys(CountrysName: 'Falkland Islands (Malvinas)', CountrysCode: 'FK'),
  Countrys(CountrysName: 'Faroe Islands', CountrysCode: 'FO'),
  Countrys(CountrysName: 'Fiji', CountrysCode: 'FJ'),
  Countrys(CountrysName: 'Finland', CountrysCode: 'FI'),
  Countrys(CountrysName: 'France', CountrysCode: 'FR'),
  Countrys(CountrysName: 'French Guiana', CountrysCode: 'GF'),
  Countrys(CountrysName: 'French Polynesia', CountrysCode: 'PF'),
  Countrys(CountrysName: 'French Southern Territories', CountrysCode: 'TF'),
  Countrys(CountrysName: 'Gabon', CountrysCode: 'GA'),
  Countrys(CountrysName: 'Gambia', CountrysCode: 'GM'),
  Countrys(CountrysName: 'Georgia', CountrysCode: 'GE'),
  Countrys(CountrysName: 'Germany', CountrysCode: 'DE'),
  Countrys(CountrysName: 'Ghana', CountrysCode: 'GH'),
  Countrys(CountrysName: 'Gibraltar', CountrysCode: 'GI'),
  Countrys(CountrysName: 'Greece', CountrysCode: 'GR'),
  Countrys(CountrysName: 'Greenland', CountrysCode: 'GL'),
  Countrys(CountrysName: 'Grenada', CountrysCode: 'GD'),
  Countrys(CountrysName: 'Guadeloupe', CountrysCode: 'GP'),
  Countrys(CountrysName: 'Guam', CountrysCode: 'GU'),
  Countrys(CountrysName: 'Guatemala', CountrysCode: 'GT'),
  Countrys(CountrysName: 'Guernsey', CountrysCode: 'GG'),
  Countrys(CountrysName: 'Guinea', CountrysCode: 'GN'),
  Countrys(CountrysName: 'Guinea-Bissau', CountrysCode: 'GW'),
  Countrys(CountrysName: 'Guyana', CountrysCode: 'GY'),
  Countrys(CountrysName: 'Haiti', CountrysCode: 'HT'),
  Countrys(
      CountrysName: 'Heard Island and Mcdonald Islands', CountrysCode: 'HM'),
  Countrys(CountrysName: 'Holy See (Vatican City State)', CountrysCode: 'VA'),
  Countrys(CountrysName: 'Honduras', CountrysCode: 'HN'),
  Countrys(CountrysName: 'Hong Kong', CountrysCode: 'HK'),
  Countrys(CountrysName: 'Hungary', CountrysCode: 'HU'),
  Countrys(CountrysName: 'Iceland', CountrysCode: 'IS'),
  Countrys(CountrysName: 'India', CountrysCode: 'IN'),
  Countrys(CountrysName: 'Indonesia', CountrysCode: 'ID'),
  Countrys(CountrysName: 'Iran, Islamic Republic Of', CountrysCode: 'IR'),
  Countrys(CountrysName: 'Iraq', CountrysCode: 'IQ'),
  Countrys(CountrysName: 'Ireland', CountrysCode: 'IE'),
  Countrys(CountrysName: 'Isle of Man', CountrysCode: 'IM'),
  Countrys(CountrysName: 'Israel', CountrysCode: 'IL'),
  Countrys(CountrysName: 'Italy', CountrysCode: 'IT'),
  Countrys(CountrysName: 'Jamaica', CountrysCode: 'JM'),
  Countrys(CountrysName: 'Japan', CountrysCode: 'JP'),
  Countrys(CountrysName: 'Jersey', CountrysCode: 'JE'),
  Countrys(CountrysName: 'Jordan', CountrysCode: 'JO'),
  Countrys(CountrysName: 'Kazakhstan', CountrysCode: 'KZ'),
  Countrys(CountrysName: 'Kenya', CountrysCode: 'KE'),
  Countrys(CountrysName: 'Kiribati', CountrysCode: 'KI'),
  Countrys(
      CountrysName: 'Korea, Democratic People\'S Republic of',
      CountrysCode: 'KP'),
  Countrys(CountrysName: 'Korea, Republic of', CountrysCode: 'KR'),
  Countrys(CountrysName: 'Kuwait', CountrysCode: 'KW'),
  Countrys(CountrysName: 'Kyrgyzstan', CountrysCode: 'KG'),
  Countrys(
      CountrysName: 'Lao People\'S Democratic Republic', CountrysCode: 'LA'),
  Countrys(CountrysName: 'Latvia', CountrysCode: 'LV'),
  Countrys(CountrysName: 'Lebanon', CountrysCode: 'LB'),
  Countrys(CountrysName: 'Lesotho', CountrysCode: 'LS'),
  Countrys(CountrysName: 'Liberia', CountrysCode: 'LR'),
  Countrys(CountrysName: 'Libyan Arab Jamahiriya', CountrysCode: 'LY'),
  Countrys(CountrysName: 'Liechtenstein', CountrysCode: 'LI'),
  Countrys(CountrysName: 'Lithuania', CountrysCode: 'LT'),
  Countrys(CountrysName: 'Luxembourg', CountrysCode: 'LU'),
  Countrys(CountrysName: 'Macao', CountrysCode: 'MO'),
  Countrys(
      CountrysName: 'Macedonia, The Former Yugoslav Republic of',
      CountrysCode: 'MK'),
  Countrys(CountrysName: 'Madagascar', CountrysCode: 'MG'),
  Countrys(CountrysName: 'Malawi', CountrysCode: 'MW'),
  Countrys(CountrysName: 'Malaysia', CountrysCode: 'MY'),
  Countrys(CountrysName: 'Maldives', CountrysCode: 'MV'),
  Countrys(CountrysName: 'Mali', CountrysCode: 'ML'),
  Countrys(CountrysName: 'Malta', CountrysCode: 'MT'),
  Countrys(CountrysName: 'Marshall Islands', CountrysCode: 'MH'),
  Countrys(CountrysName: 'Martinique', CountrysCode: 'MQ'),
  Countrys(CountrysName: 'Mauritania', CountrysCode: 'MR'),
  Countrys(CountrysName: 'Mauritius', CountrysCode: 'MU'),
  Countrys(CountrysName: 'Mayotte', CountrysCode: 'YT'),
  Countrys(CountrysName: 'Mexico', CountrysCode: 'MX'),
  Countrys(CountrysName: 'Micronesia, Federated States of', CountrysCode: 'FM'),
  Countrys(CountrysName: 'Moldova, Republic of', CountrysCode: 'MD'),
  Countrys(CountrysName: 'Monaco', CountrysCode: 'MC'),
  Countrys(CountrysName: 'Mongolia', CountrysCode: 'MN'),
  Countrys(CountrysName: 'Montserrat', CountrysCode: 'MS'),
  Countrys(CountrysName: 'Morocco', CountrysCode: 'MA'),
  Countrys(CountrysName: 'Mozambique', CountrysCode: 'MZ'),
  Countrys(CountrysName: 'Myanmar', CountrysCode: 'MM'),
  Countrys(CountrysName: 'Namibia', CountrysCode: 'NA'),
  Countrys(CountrysName: 'Nauru', CountrysCode: 'NR'),
  Countrys(CountrysName: 'Nepal', CountrysCode: 'NP'),
  Countrys(CountrysName: 'Netherlands', CountrysCode: 'NL'),
  Countrys(CountrysName: 'Netherlands Antilles', CountrysCode: 'AN'),
  Countrys(CountrysName: 'New Caledonia', CountrysCode: 'NC'),
  Countrys(CountrysName: 'New Zealand', CountrysCode: 'NZ'),
  Countrys(CountrysName: 'Nicaragua', CountrysCode: 'NI'),
  Countrys(CountrysName: 'Niger', CountrysCode: 'NE'),
  Countrys(CountrysName: 'Nigeria', CountrysCode: 'NG'),
  Countrys(CountrysName: 'Niue', CountrysCode: 'NU'),
  Countrys(CountrysName: 'Norfolk Island', CountrysCode: 'NF'),
  Countrys(CountrysName: 'Northern Mariana Islands', CountrysCode: 'MP'),
  Countrys(CountrysName: 'Norway', CountrysCode: 'NO'),
  Countrys(CountrysName: 'Oman', CountrysCode: 'OM'),
  Countrys(CountrysName: 'Pakistan', CountrysCode: 'PK'),
  Countrys(CountrysName: 'Palau', CountrysCode: 'PW'),
  Countrys(CountrysName: 'Palestinian Territory, Occupied', CountrysCode: 'PS'),
  Countrys(CountrysName: 'Panama', CountrysCode: 'PA'),
  Countrys(CountrysName: 'Papua New Guinea', CountrysCode: 'PG'),
  Countrys(CountrysName: 'Paraguay', CountrysCode: 'PY'),
  Countrys(CountrysName: 'Peru', CountrysCode: 'PE'),
  Countrys(CountrysName: 'Philippines', CountrysCode: 'PH'),
  Countrys(CountrysName: 'Pitcairn', CountrysCode: 'PN'),
  Countrys(CountrysName: 'Poland', CountrysCode: 'PL'),
  Countrys(CountrysName: 'Portugal', CountrysCode: 'PT'),
  Countrys(CountrysName: 'Puerto Rico', CountrysCode: 'PR'),
  Countrys(CountrysName: 'Qatar', CountrysCode: 'QA'),
  Countrys(CountrysName: 'Reunion', CountrysCode: 'RE'),
  Countrys(CountrysName: 'Romania', CountrysCode: 'RO'),
  Countrys(CountrysName: 'Russian Federation', CountrysCode: 'RU'),
  Countrys(CountrysName: 'RWANDA', CountrysCode: 'RW'),
  Countrys(CountrysName: 'Saint Helena', CountrysCode: 'SH'),
  Countrys(CountrysName: 'Saint Kitts and Nevis', CountrysCode: 'KN'),
  Countrys(CountrysName: 'Saint Lucia', CountrysCode: 'LC'),
  Countrys(CountrysName: 'Saint Pierre and Miquelon', CountrysCode: 'PM'),
  Countrys(
      CountrysName: 'Saint Vincent and the Grenadines', CountrysCode: 'VC'),
  Countrys(CountrysName: 'Samoa', CountrysCode: 'WS'),
  Countrys(CountrysName: 'San Marino', CountrysCode: 'SM'),
  Countrys(CountrysName: 'Sao Tome and Principe', CountrysCode: 'ST'),
  Countrys(CountrysName: 'Saudi Arabia', CountrysCode: 'SA'),
  Countrys(CountrysName: 'Senegal', CountrysCode: 'SN'),
  Countrys(CountrysName: 'Serbia and Montenegro', CountrysCode: 'CS'),
  Countrys(CountrysName: 'Seychelles', CountrysCode: 'SC'),
  Countrys(CountrysName: 'Sierra Leone', CountrysCode: 'SL'),
  Countrys(CountrysName: 'Singapore', CountrysCode: 'SG'),
  Countrys(CountrysName: 'Slovakia', CountrysCode: 'SK'),
  Countrys(CountrysName: 'Slovenia', CountrysCode: 'SI'),
  Countrys(CountrysName: 'Solomon Islands', CountrysCode: 'SB'),
  Countrys(CountrysName: 'Somalia', CountrysCode: 'SO'),
  Countrys(CountrysName: 'South Africa', CountrysCode: 'ZA'),
  Countrys(
      CountrysName: 'South Georgia and the South Sandwich Islands',
      CountrysCode: 'GS'),
  Countrys(CountrysName: 'Spain', CountrysCode: 'ES'),
  Countrys(CountrysName: 'Sri Lanka', CountrysCode: 'LK'),
  Countrys(CountrysName: 'Sudan', CountrysCode: 'SD'),
  Countrys(CountrysName: 'Suriname', CountrysCode: 'SR'),
  Countrys(CountrysName: 'Svalbard and Jan Mayen', CountrysCode: 'SJ'),
  Countrys(CountrysName: 'Swaziland', CountrysCode: 'SZ'),
  Countrys(CountrysName: 'Sweden', CountrysCode: 'SE'),
  Countrys(CountrysName: 'Switzerland', CountrysCode: 'CH'),
  Countrys(CountrysName: 'Syrian Arab Republic', CountrysCode: 'SY'),
  Countrys(CountrysName: 'Taiwan, Province of China', CountrysCode: 'TW'),
  Countrys(CountrysName: 'Tajikistan', CountrysCode: 'TJ'),
  Countrys(CountrysName: 'Tanzania, United Republic of', CountrysCode: 'TZ'),
  Countrys(CountrysName: 'Thailand', CountrysCode: 'TH'),
  Countrys(CountrysName: 'Timor-Leste', CountrysCode: 'TL'),
  Countrys(CountrysName: 'Togo', CountrysCode: 'TG'),
  Countrys(CountrysName: 'Tokelau', CountrysCode: 'TK'),
  Countrys(CountrysName: 'Tonga', CountrysCode: 'TO'),
  Countrys(CountrysName: 'Trinidad and Tobago', CountrysCode: 'TT'),
  Countrys(CountrysName: 'Tunisia', CountrysCode: 'TN'),
  Countrys(CountrysName: 'Turkey', CountrysCode: 'TR'),
  Countrys(CountrysName: 'Turkmenistan', CountrysCode: 'TM'),
  Countrys(CountrysName: 'Turks and Caicos Islands', CountrysCode: 'TC'),
  Countrys(CountrysName: 'Tuvalu', CountrysCode: 'TV'),
  Countrys(CountrysName: 'Uganda', CountrysCode: 'UG'),
  Countrys(CountrysName: 'Ukraine', CountrysCode: 'UA'),
  Countrys(CountrysName: 'United Arab Emirates', CountrysCode: 'AE'),
  Countrys(CountrysName: 'United Kingdom', CountrysCode: 'GB'),
  Countrys(CountrysName: 'United States', CountrysCode: 'US'),
  Countrys(
      CountrysName: 'United States Minor Outlying Islands', CountrysCode: 'UM'),
  Countrys(CountrysName: 'Uruguay', CountrysCode: 'UY'),
  Countrys(CountrysName: 'Uzbekistan', CountrysCode: 'UZ'),
  Countrys(CountrysName: 'Vanuatu', CountrysCode: 'VU'),
  Countrys(CountrysName: 'Venezuela', CountrysCode: 'VE'),
  Countrys(CountrysName: 'Viet Nam', CountrysCode: 'VN'),
  Countrys(CountrysName: 'Virgin Islands, British', CountrysCode: 'VG'),
  Countrys(CountrysName: 'Virgin Islands, U.S.', CountrysCode: 'VI'),
  Countrys(CountrysName: 'Wallis and Futuna', CountrysCode: 'WF'),
  Countrys(CountrysName: 'Western Sahara', CountrysCode: 'EH'),
  Countrys(CountrysName: 'Yemen', CountrysCode: 'YE'),
  Countrys(CountrysName: 'Zambia', CountrysCode: 'ZM'),
  Countrys(CountrysName: 'Zimbabwe', CountrysCode: 'ZW'),
];
List supportedCurrencyList = [
  'BTC - Bitcoin - ₿',
  'USD - United States Dollar - \$',
  'AED - United Arab Emirates Dirham - د.إ',
  'ARS - Argentine Peso - \$',
  'AUD - Australian Dollar - \$',
  'BDT - Bangladeshi Taka - ৳',
  'BHD - Bahraini Dinar - .د.ب',
  'BMD - Bermudan Dollar - \$',
  'BRL - Brazilian Real - R\$',
  'CAD - Canadian Dollar - \$',
  'CHF - Swiss Franc - CHF',
  'CLP - Chilean Peso - \$',
  'CNY - Chinese Yuan - ¥',
  'CZK - Czech Republic Koruna - Kč',
  'DKK - Danish Krone - kr',
  'EUR - Euro - €',
  'GBP - British Pound Sterling - £',
  'HKD - Hong Kong Dollar - \$',
  'HUF - Hungarian Forint - Ft',
  'IDR - Indonesian Rupiah - Rp',
  'ILS - Israeli New Sheqel - ₪',
  'INR - Indian Rupee - ₹',
  'JPY - Japanese Yen - ¥',
  'KRW - South Korean Won - ₩',
  'KWD - Kuwaiti Dinar - د.ك',
  'LKR - Sri Lankan Rupee - Rs',
  'MMK - Myanma Kyat - Ks',
  'MXN - Mexican Peso - \$',
  'MYR - Malaysian Ringgit - RM',
  'NGN - Nigerian Naira - ₦',
  'NOK - Norwegian Krone - kr',
  'NZD - New Zealand Dollar - \$',
  'PHP - Philippine Peso - ₱',
  'PKR - Pakistani Rupee - ₨',
  'PLN - Polish Zloty - zł',
  'RUB - Russian Ruble - ₽',
  'SAR - Saudi Riyal - ﷼',
  'SEK - Swedish Krona - kr',
  'SGD - Singapore Dollar - \$',
  'THB - Thai Baht - ฿',
  'TRY - Turkish Lira - ₺',
  'TWD - New Taiwan Dollar - \$',
  'UAH - Ukrainian Hryvnia - ₴',
  'VEF - Venezuelan Bolívar Fuerte (Old) - Bs F',
  'VND - Vietnamese Dong - ₫',
  'ZAR - South African Rand - R',
  'XDR - Special Drawing Rights - XDR',
  'XAG - Silver Ounce - XAG',
  'XAU - Gold Ounce - XAU'
];
